### ISSUE TITLE
Now broken

### ISSUE THREAD

**Issue by momala454** [KyranRana/cloudflare-bypass#164]
Since today, the script is broken because the url on the form is encoded with &xxx;, so the script tries to submit to url containing &amp;

the fix on UAMPageFormParams function on main/Model/UAM/UAMPageFormParams.php

modify like this
return new UAMPageFormParams(
            $sMatches[1],
            $jschlVcMatches[1],
            $passMatches[1],
            self::getJschlAnswerFromPage($pageAttributes),
            htmlspecialchars_decode($urlMatches[1])
        );

**Comment by gergokee** [comment]
Well for me it is still not working with this change:

Tried reaching this page:
https://predb.me/?search=720p

"[ERROR] UAM (retry: 0) -> clearance cookie missing! Unknown error -> CF clearance could not be found!"

**Comment by judgdredd** [comment]
Yeah it's definitely NOT working. I've tested it on http://medium.com https://torrentz2.eu and various others. My script that was working for over 7 months just stopped working recently due to the bypasser not solving the cloudflare problem and instead returns the usual

`          setTimeout(function(){\n
            var s,t,o,p,b,r,e,a,k,i,n,g,f, CNVCtJR={"USHdsl":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![ ▶
            g = String.fromCharCode;\n
            o = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";\n
            e = function(s) {\n
              s += "==".slice(2 - (s.length & 3));\n
              var bm, r = "", r1, r2, i = 0;\n
              for (; i < s.length;) {\n
                  bm = o.indexOf(s.charAt(i++)) << 18 | o.indexOf(s.charAt(i++)) << 12\n
                          | (r1 = o.indexOf(s.charAt(i++))) << 6 | (r2 = o.indexOf(s.charAt(i++)));\n
                  r += r1 === 64 ? g(bm >> 16 & 255)\n
                          : r2 === 64 ? g(bm >> 16 & 255, bm >> 8 & 255)\n
                          : g(bm >> 16 & 255, bm >> 8 & 255, bm & 255);\n
              }\n
              return r;\n`

**Comment by momala454** [comment]
i tried both url http://medium.com https://torrentz2.eu  and they works.
Make sure you put all of those headers (with different values if you want, but they must be present)
'Connection: Keep-Alive', 'Accept-Language: *', 
'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0', 'Accept: */*', 
'Accept-Encoding: deflate, gzip', 
'Upgrade-Insecure-Requests: 1'

**Comment by momala454** [comment]
actually i'll reopen until another release is done with the change for this bug

**Comment by judgdredd** [comment]
This is some of the code re: the headers
![Screenshot from 2020-03-13 14-14-53](https://user-images.githubusercontent.com/4535325/76586503-2106fe80-6535-11ea-9f7d-74843e1f32b7.png)
And this is the result
![Screenshot from 2020-03-13 14-16-16](https://user-images.githubusercontent.com/4535325/76586629-8529c280-6535-11ea-816c-80370ccb70e8.png)

**Comment by judgdredd** [comment]
This might be a bit messy but the below is the dump output in a terminal of https://torrentz2.eu using your CFCurlTest.php file directly.

`"""
<!DOCTYPE HTML>\n
<html lang="en-US">\n
<head>\n
  <meta charset="UTF-8" />\n
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n
  <meta name="robots" content="noindex, nofollow" />\n
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />\n
  <meta http-equiv="refresh" content="12">\n
  <title>Just a moment...</title>\n
  <style type="text/css">\n
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}\n
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}\n
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}\n
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}\n
    p, .attribution, {text-align: center;}\n
    #spinner {margin: 0 auto 30px auto; display: block;}\n
    .attribution {margin-top: 32px;}\n
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }\n
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }\n
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}\n
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}\n
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}\n
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }\n
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }\n
    a:hover{color: #f4a15d}\n
    .attribution{font-size: 16px; line-height: 1.5;}\n
    .ray_id{display: block; margin-top: 8px;}\n
  </style>\n
\n
    <script type="text/javascript">\n
  //<![CDATA[\n
  (function(){\n
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },\n
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};\n
    b(function(){\n
      var a = document.getElementById('cf-content');a.style.display = 'block';\n
      var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);\n
      var trkjs = isIE ? new Image() : document.createElement('img');\n
      trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=5732b6e44b776561");\n
      trkjs.id = "trk_jschal_js";\n
      trkjs.setAttribute("alt", "");\n
      document.body.appendChild(trkjs);\n
      setTimeout(function(){\n
        var s,t,o,p,b,r,e,a,k,i,n,g,f, ejcfWtj={"McWSUKeOQALD":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]))};\n
        g = String.fromCharCode;\n
        o = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";\n
        e = function(s) {\n
          s += "==".slice(2 - (s.length & 3));\n
          var bm, r = "", r1, r2, i = 0;\n
          for (; i < s.length;) {\n
              bm = o.indexOf(s.charAt(i++)) << 18 | o.indexOf(s.charAt(i++)) << 12\n
                      | (r1 = o.indexOf(s.charAt(i++))) << 6 | (r2 = o.indexOf(s.charAt(i++)));\n
              r += r1 === 64 ? g(bm >> 16 & 255)\n
                      : r2 === 64 ? g(bm >> 16 & 255, bm >> 8 & 255)\n
                      : g(bm >> 16 & 255, bm >> 8 & 255, bm & 255);\n
          }\n
          return r;\n
        };\n
        t = document.createElement('div');\n
        t.innerHTML="<a href='/'>x</a>";\n
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];\n
        t = t.substr(r.length); t = t.substr(0,t.length-1); k = 'cf-dn-WcZg';\n
        a = document.getElementById('jschl-answer');\n
        f = document.getElementById('challenge-form');\n
        ;ejcfWtj.McWSUKeOQALD*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+[])+(+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]));ejcfWtj.McWSUKeOQALD*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));ejcfWtj.McWSUKeOQALD*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((+!![]+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(+!![]));ejcfWtj.McWSUKeOQALD*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]));ejcfWtj.McWSUKeOQALD+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]));ejcfWtj.McWSUKeOQALD-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![])+(+[]));ejcfWtj.McWSUKeOQALD*=function(p){var p = eval(eval(e("ZG9jdW1l")+(undefined+"")[1]+(true+"")[0]+(+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+g(103)+(true+"")[3]+(true+"")[0]+"Element"+g(66)+(NaN+[Infinity])[10]+"Id("+g(107)+")."+e("aW5uZXJIVE1M"))); return +(p)}();ejcfWtj.McWSUKeOQALD+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));ejcfWtj.McWSUKeOQALD-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![]))/+((+!![]+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]));a.value = (+ejcfWtj.McWSUKeOQALD).toFixed(10); '; 121'\n
        f.action += location.hash;\n
        f.submit();\n
      }, 4000); /*eoc*/\n
    }, false);\n
  })();\n
  //]]>\n
</script>\n
\n
\n
</head>\n
<body>\n
  <table width="100%" height="100%" cellpadding="20">\n
    <tr>\n
      <td align="center" valign="middle">\n
          <div class="cf-browser-verification cf-im-under-attack">\n
  <noscript>\n
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>\n
  </noscript>\n
  <div id="cf-content" style="display:none">\n
    <!-- <a href="https://directoryblacklist.com/aslope.php?to=7">table</a> -->\n
    <div id="cf-bubbles">\n
      <div class="bubbles"></div>\n
      <div class="bubbles"></div>\n
      <div class="bubbles"></div>\n
    </div>\n
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> torrentz2.eu.</h1>\n
    \n
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>\n
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>\n
  </div>\n
   \n
  <form id="challenge-form" action="/?__cf_chl_jschl_tk__=cb1a489f8f73b59fb5f0d71692208615391bf036-1584070625-0-AX5nW4DmwDJ0-f1ccsxM9jbzbrDOE_oIgJYN-8qE41EyhFqCyMt4OL5Zr59LHP4qF7BgXFk2yf3pqP5_CkN8djf3QxMeSJFS_csckHNV-_tu8kO_phWVqyBYq2NVc8qTAeXf3GhZfu_OjURQUGfnHlXEDaO1RWXquY23DLOPfRjyjVnhDVh5Kwjw50Q_8WSHO_Inl9_mCnvcx4k9Qqn_a2L3P-sqJK0EFr6QkA3uzGA8p4kWsxTEfLf8QfeIi3JMEubXOXNXcvxO5kPBCMbME9Q" method="POST" enctype="application/x-www-form-urlencoded">\n
    <input type="hidden" name="r" value="bc27268ba984c1f1ca05e4ff4d23a826fb77a6fc-1584070625-0-AZNuFKt5ZaiP6KhVJPt9C+GFdVZ15i/PzN9QQoV3V0lOkP/5jAMmQXRJ5PpslnAifUdiCv/8eZXmcx2PSSFuUTuPo6m2eHDzml5Weku/EkOlk1MdBhG16mp/SkJmRMiw68x6lNAdS2go0+iORX/fOeM0E2/QGR2bQqHAVCBfPkvepQ2YIq19Z94rmyQZU6yLObeMAVLoQCz9gyvcUIEIhKGRDgISIYbPeIdQ+jEtymyzFef4PmfbC0OvR+XzXUYpADTxrXPxHQy6uOpQKRJeYh1Vyu9RBJcMT3EBg13eRZis16XL9nt2Dx5pew/9ig930KpGTfyMKxiGj0Hrar10q6OHlhIQ3KtXRBZBCfZaVbwW65mAOgxtcVJB6sIZQPvt8u5w9kh038tf5TV8AiMBLbL4bnnhmI7UwMds4w9DhhUXsH0Cbe/oBZn+Dz5BZIJjYp0BGoDMc6L+tJoaFUgyeobSz53+2t0WHZ1i+69bHTkdsQGvL1UaGr+/unF3D4M5BLu+qEsoaXU4xm8hAHCM1ecm4IQcAk2l6N/AfifdqQQWrsQonoNlmBNsf+pYRkBo6PTmIW5T1A9WZFH+uAnKJJ9VUaySxN8mu6gT1IPltbbRMhD3M7GIedm0oxWhmFWxjHhhL2Z3PDZfpHRTMa8jeiiYzAyXqOo12ZC/zZVb+2MarEgTCemIw4RHN5Intc8qp0pmH765IpFZCgtDP/3nIQBQLQ1fxNkw1dJEHcF2JV63uMJq31tBAQarBTEQ7OvImag4UDDwxFRMOna+KbEjFvn0p/RsBQoR+NaVnFPJXr5sMkL/RoVIZcKQWSFLqmxYT5T+12bX1S6G551efJAU0dL/Ul/Ad2z3I4HAN4sG8In++MU9KAGuQwVst4vbvQiTXH8F7lEyoi9Di4eqTer55UcvupXzJNRtgQpe/Vx9MgtepNvry/i7CanpugEzrdJZbtKnKpj3AMaMcvHp12zi1AOSZk1U4eALSOgrkdRuIvclpr3NWGY9KCyPxiI7zzibMAnm8+RCKqJSH/t9ZT5OBZ1VHNbMJw0tXRxbff1EqALg/1lbxZZcpQ5MCWDYDkP7MgYFyXKACddaBZ1eJSCmeiUV9fxq9BWnl8mgUoVqHVDdwV24Wj8qrw5fiXiG1MGrdJjLDpQ7/H1eLVv0F6qnT4QPhTIVH6j0DiOEdP6qKXMIsTTTiCyZCCQv+tn5bcCjActjJmoCSzk4IMcP4+KQhvKgWtI7YYCFWaq0/UPUwNR9yca5WQpumk0+1nVNpC62bdbEV31qkAQtNYjJl49at8ZujG6aG4GIfaGqeVpFzx4mDzcz3a4nuRHuBYlqzdP5B5ElXXrrAI8wQ96hTRg4Z+e1bw22xjISjLVqI2ewr8X8Woo/nvgplZLND23tKhKj9qnNqbZ1gEZseK49vbx00je3AfA877x9n+KRmApI3ociyUXxOtwO7KQzJXN0aWGQhnN/437Jo320vGkZ1e1AvVk="></input>\n
    <input type="hidden" name="jschl_vc" value="bc7f70bf2aaf26dedaf3cba983e68a90"/>\n
    <input type="hidden" name="pass" value="1584070629.964-12prmqqSYp"/>\n
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>\n
  </form>\n
  \n
  <div style="display:none;visibility:hidden;" id="cf-dn-WcZg">+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]))</div>\n
  \n
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=5732b6e44b776561')"> </div>\n
</div>\n
\n
          \n
          <div class="attribution">\n
            DDoS protection by <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank">Cloudflare</a>\n
            <br />\n
            <span class="ray_id">Ray ID: <code>5732b6e44b776561</code></span>\n
          </div>\n
      </td>\n
     \n
    </tr>\n
  </table>\n
</body>\n
</html>\n`

**Comment by judgdredd** [comment]
Okay.. So it's important to note i've been using the version pulled and updated from composer require kyranrana/cloudflare-bypass

That being said i did the patch tweaks above to no avail.

I just downloaded the zip file directly from here and unpacked it in the vendor dir and now everything is working. So what is obtained via composer and what fixed are provided here don't work. I'd say update the composer package to what's in the master.zip here.

**Comment by momala454** [comment]
yeah i don't get why he don't make a new release

**Comment by wynasoft1** [comment]
Hi guys can anybody share a demo for get contents?

thanks

regards

**Comment by jaymoulin** [comment]
@momala454 I'm pretty sure maintaining this kind of product is really time consuming and Kyran prefer spending time on other things. I already gave him some recommendations for this package to be more usable here : https://github.com/KyranRana/cloudflare-bypass/issues/157

As I am, and many other users are, stuck with this package release process, I published a fork https://github.com/jaymoulin/cloudflare-bypass which is just a usable automatically updated fork of this repo.

Basically, every time a PR is merged, or a commit is pushed to this master, my package will update and make a usable unstable release (dev-master) available on packagist, therefore, composer (`composer require jaymoulin/cloudflare-bypass:dev-master`).

Also, I added a functional test case to check with both https://torrentz2.eu and https://medium.com on GitHub's servers to check the package's behaviour ![CI](https://github.com/jaymoulin/cloudflare-bypass/workflows/CI/badge.svg) and details (https://github.com/jaymoulin/cloudflare-bypass/actions?query=workflow%3ACI)

As this package is a `unstable` package, you all have to decrease `minimum-stability` of your `composer.json` file to `dev` (and adding `prefer-stable` to `true` when possible). Sorry, but this is mandatory as https://github.com/KyranRana/cloudflare-bypass/issues/157 is still open.

I'm not really happy I had to do this but I understand some of Kyran's choices.
I hope this is only a temporary fix and it will unstuck people.

**Comment by gergokee** [comment]
Well i tried it again, but still can't access https://torrentz2.eu 
Tried from 2 different servers:
 - first server error: **"clearance cookie missing! Unknown error -> CF clearance could not be found!"**
 - second server error: **"[ERROR] Captcha (retry: 1) -> not supported! Unknown error -> Captcha page is not supported!"**

**Comment by nitemare** [comment]
i'm getting the same errors for https://torrentz2.eu and https://torrentz2.is
